### ISSUE TITLE
見てたぞのハイライト

### ISSUE THREAD

**Issue by mirror-kt** [brokenManager/OreOreBot#112]
editedの監視、コードブロックの言語指定に
```diff
- test1
+ test
```
とすればシンタックスハイライトが効くのでやってください
4文字追加するだけですね

**Comment by Colk-tech** [comment]
はえーーーーすごい
初めて知ったゾ

**Comment by Colk-tech** [comment]
'diffiro'で作業
ロジックの変更はないのでブランチロックは一時的に解除します
