### ISSUE TITLE
Voice Diffについて、同一ユーザーの通知は一定時間内に出す回数を制限する

### ISSUE THREAD

**Issue by Colk-tech** [brokenManager/OreOreBot#142]
通知がテロすぎる、やめてクレメンス

**Comment by loxygenK** [comment]
I'm going to work with this extremely emergency issue after drinking some cups of nice 麦茶.

**Comment by kawaemon** [comment]
麦茶 is uncountable.

**Comment by kawaemon** [comment]
Nice work @siketyan .

**Comment by shun-shobon** [comment]
![スクリーンショット 2020-08-10 21 42 31](https://user-images.githubusercontent.com/37236438/89783758-70883f80-db52-11ea-9153-3d86b9c119f1.png)

**Comment by Colk-tech** [comment]
error[E0234]: "s" with uncountable noun error (liquid) 
   --> https://github.com/approvers/OreOreBot/issues/142#issuecomment-671330128
    |
1   | I'm going to work with this extremely emergency issue after drinking some nice 麦茶s.
    |                                                                                                                                         ^^^^^ object "麦茶" is uncountable.

**Comment by loxygenK** [comment]
much appreciation to everyone, my English is extremely poor...

**Comment by Colk-tech** [comment]
No, no, not like that 💦 
And, is your English really poor so that you should apologize?

**Comment by kawaemon** [comment]
🚨OSS old man was detected.🚨

**Comment by shun-shobon** [comment]
```
＿人人人人人＿
＞　OSS oji　＜
￣Y^Y^Y^Y^Y^￣
```

**Comment by Colk-tech** [comment]
fuck OSS oji off

**Comment by shun-shobon** [comment]
![スクリーンショット 2020-08-10 21 53 41](https://user-images.githubusercontent.com/37236438/89784651-fbb60500-db53-11ea-8a66-72e3867629bf.png)

**Comment by loxygenK** [comment]
i'll add an alias to the server

**Comment by soshiharami** [comment]
OSS Oji San

**Comment by loxygenK** [comment]
a genius idea it is

**Comment by loxygenK** [comment]
閉じんの忘れてた、閉じます
