### ISSUE TITLE
将来的に分指定でもmsg送れるようにしませんか？

### ISSUE THREAD

**Issue by Colk-tech** [brokenManager/OreOreBot#18]
@isso0424 
あとこれは提案なんですけど、on_ready()時に現在の秒数を取得して、ちょうどn分0秒のときに60秒ごとにループできるようにしませんか？

**Comment by Colk-tech** [comment]
related issues: #17

**Comment by loxygenK** [comment]
処理重くなりそう…重くなりそうじゃない？
about this: https://github.com/brokenManager/OreOreBot/issues/18#issue-574839045

**Comment by Colk-tech** [comment]
いまのところループ回数が50秒に1度なので負担は多分変わらないです

**Comment by isso0424** [comment]
60秒に1回だとバグる可能性あるから50秒にしてるだけやで

**Comment by Colk-tech** [comment]
理解した
まあ多少はね

**Comment by Colk-tech** [comment]
実現自体は簡単なのでいったんclose
