### ISSUE TITLE
#<repo>/…のあとにコマンドを叩けたら…たいへん…えっち…

### ISSUE THREAD

**Issue by loxygenK** [brokenManager/OreOreBot#3]
今考えてるのは
- `top` or `t` → リポジトリのトップ
- `ブランチ名/ディレクトリ/...` → 指定ディレクトリ／ファイル
- `issues` or `i` → Issueのリスト
- `pulls` or `p` → PRのリスト

**Comment by loxygenK** [comment]
`cmds`ブランチで動かしますね

**Comment by isso0424** [comment]
素晴らしい

**Comment by loxygenK** [comment]
あったら射精するぐらいには便利だと思うの
