### ISSUE TITLE
時間系のbaseをまとめる

### ISSUE THREAD

**Issue by Colk-tech** [brokenManager/OreOreBot#81]
・インスタンスをひとつだけ生成して時間になったら機能を呼び出す
・必要な数だけインスタンスを生成してそこから各機能を呼び出す
どちらかで実装

**Comment by isso0424** [comment]
今の状態でもインスタンスは1つやで
ただ何故かループ処理が増えてる

これは原因不明のon_ readyの呼び出しによるもの

**Comment by Colk-tech** [comment]
on_readyって複数回呼ばれるのか...(困惑)

**Comment by Colk-tech** [comment]
on_readyとは(哲学)

**Comment by Colk-tech** [comment]
なるほど、強制排除できそう

**Comment by isso0424** [comment]
†***強制排除***†するわ
`PLEASE_ON_READY_ONETIME`で作業する

**Comment by Colk-tech** [comment]
†***強制排除***†草
たすかる

**Comment by Colk-tech** [comment]
ブランチ名懇願で草

**Comment by isso0424** [comment]
直したからレビュー頼む

**Comment by Colk-tech** [comment]
うい
