### ISSUE TITLE
消してほしい時間じゃね？

### ISSUE THREAD

**Issue by UniokaWorld** [brokenManager/OreOreBot#94]
![image](https://user-images.githubusercontent.com/52340378/78711286-b1c4d480-7951-11ea-9063-a034c22d8f5d.png)

**Comment by Colk-tech** [comment]
これは似ている処理から持ってくるときに間違えたやつですね
修正します`bugs_fix`で修正されます

**Comment by Colk-tech** [comment]
828c5ccacaf0070fc740bdfb54dbe23fd16042aa #95 にて修正済み
